### ISSUE TITLE
已有项目转换报错 include 这种不支持吗?

### ISSUE THREAD

**Issue by xpf0000** [weidian-inc/hera-cli#1]
小程序里面是这样写的
<include src="search.wxml" wx:if="{{item.type=='search'}}" />

转换的时候 提示这个
yb_shop/pages/index/index.wxml=> ParseImports Error <=Error: ENOENT: no such file or directory, open 'yb_shop/pages/index/search.wxml" wx:if="{{item.type=='search'}}'
yb_shop/pages/index/index.wxml==> Parse Page Error: { [Error: ENOENT: no such file or directory, open 'yb_shop/pages/index/search.wxml" wx:if="{{item.type=='search'}}']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'yb_shop/pages/index/search.wxml" wx:if="{{item.type==\'search\'}}' }
yb_shop/pages/power/index.wxml=> ParseImports Error <=Error: ENOENT: no such file or directory, open 'yb_shop/pages/index/search.wxml" wx:if="{{item.type=='search'}}'
但是这个文件是有的 yb_shop/pages/index/search.wxml  
这个是怎么回事?

**Comment by xpf0000** [comment]
问题找到了 正则有问题  改下就好了

**Comment by refgd** [comment]
怎么改的?能说一下吗
